# Generated by Django 2.2.28 on 2023-08-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_1', models.CharField(max_length=255)),
                ('amenity_2', models.CharField(blank=True, max_length=255, null=True)),
                ('amenity_3', models.CharField(blank=True, max_length=255, null=True)),
                ('amenity_4', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
